name: Release
on:
  push:
    branches:
      - main
    paths:
      - "package.json"
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test.yml
  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-test-env
      - name: Build package
        run: pnpm build
      - name: Publish deferredjson
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
